### ISSUE TITLE
Translating docs into other languages

### ISSUE THREAD

**Issue by artcygn** [radicle-dev/radicle-docs#117]
Docusaurus allows for useful translation functionality using [Crowdin](https://docusaurus.io/).

**Comment by artcygn** [comment]
Docusaurus allows for useful translation functionality using [Crowdin](https://docusaurus.io/).

**Comment by sebastinez** [comment]
We are currently doing a big overhaul of the entire documentation, but once more stable, I think it would be nice to have the documentation in more than one language.
wdyt @joelhans?

**Comment by joelhans** [comment]
Closing, as we're undergoing yet another major change in purpose and architecture for documentation and can't prioritize translations for the foreseeable future.
