### ISSUE TITLE
No API Documentation

### ISSUE THREAD

**Issue by bonedaddy** [radicle-dev/radicle-docs#121]
While running the upstream client I noticed it was making many API requests to the underlying radicle node. It doesn't appear that this API is documented on the website. It would be great if there was API documentation as it would make it much easier to build applications ontop of the radicel node.

**Comment by sebastinez** [comment]
Hi @bonedaddy, sorry for the no-show.
The API that Upstream is querying is internal and will eventually be deprecated.

If you want to build applications on top of the Radicle protocol I can suggest to you either look into the http-api of the radicle-client-services (where the API will be documented soon).
https://app.radicle.network/alt-clients.radicle.eth/rad:git:hnrkk9c4zt9thuxhwi1ukxqcrs5tmhbtcsony/tree/0cbc2212494f9e26e227729a584838f5e9772305

Or keep an eye out for the daemon that the radicle-link team is building.
https://github.com/radicle-dev/radicle-link

**Comment by sebastinez** [comment]
@bonedaddy feel free to visit the radicle-client-services/http-api docs.
https://github.com/radicle-dev/radicle-client-services/tree/sebastinez/http-api-doc/http-api/docs

They are still a WIP but its the most public API we have atm.

Closing this issue for now, let me know if you have any further issue
