### ISSUE TITLE
Text suggestion for "Running a seed node" section

### ISSUE THREAD

**Issue by Mi-Lan** [radicle-dev/radicle-docs#124]
Would be good to add some reminder to restart terminal after installing rust since it will display error after running command  `cargo run -p radicle-keyutil -- --filename ~/.radicle-seed/secret.key`

**Comment by rudolfs** [comment]
Sounds like a good idea. Would you be up for opening a PR for this?

**Comment by Mi-Lan** [comment]
Sounds good! @rudolfs can you give me permission?

**Comment by rudolfs** [comment]
@Mi-Lan I think you should be able to make a fork and open a pull request from there:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.

Let me know if that doesn't work.
