### ISSUE TITLE
Airtable calender suggestion

### ISSUE THREAD

**Issue by Mi-Lan** [radicle-dev/radicle-docs#125]
- Under Get involved section it would be cool to have airtable with the meetings like the one coming up so it will be easier for people to keep track
- We are working on something similar in dxDao and it looks like this 
![Screenshot 2021-03-03 at 16 52 18](https://user-images.githubusercontent.com/33226956/109833180-55d9fd00-7c41-11eb-924f-ff97a53277d4.png)

**Comment by sebastinez** [comment]
Hi @Mi-Lan thank you for opening this issue, we are currently working on a big overhaul of much of the documentation, please feel free to propose DAO tooling and help on our Discord server https://discord.gg/dZK4TxaU2v

**Comment by sebastinez** [comment]
Will close this issue for now.
