### ISSUE TITLE
Link to "how to add this to your shell" doesn't actually explain how

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-docs#128]
This "read more" link
![image](https://user-images.githubusercontent.com/4406983/111454749-4b296880-8715-11eb-9437-0eed48b90ba2.png)

leads to this:
![image](https://user-images.githubusercontent.com/4406983/111454776-541a3a00-8715-11eb-8a5c-1aa561c82823.png)

…which doesn't explain it at all.

**Comment by brandonhaslegs** [comment]
So the link should either be removed, or the docs should explain how to add something to your shell.

**Comment by joelhans** [comment]
This part of the docs has been removed (well, technically hidden) by #166 and #165, and this feature/process is obsolete now, I'll go ahead and close this.
