### ISSUE TITLE
Update seedling.radicle.xyz to setzling.radicle.xyz

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-docs#131]
- [ ] ![image](https://user-images.githubusercontent.com/4406983/114262515-ada61980-99e0-11eb-81bf-244637e87b9d.png)

- [ ] ![image](https://user-images.githubusercontent.com/4406983/114262526-c0b8e980-99e0-11eb-9639-ee6a81d283aa.png)

- [ ] ![image](https://user-images.githubusercontent.com/4406983/114262535-cc0c1500-99e0-11eb-8df3-b15a95da6d57.png)

**Comment by brandonhaslegs** [comment]
TBH it's a bit of a mess to rename seedling.radicle.xyz to setzling.radicle.xyz. Just quite confusing since we've linked to it so many times.

**Comment by xla** [comment]
> TBH it's a bit of a mess to rename seedling.radicle.xyz to setzling.radicle.xyz. Just quite confusing since we've linked to it so many times.

We can't continue using seedling as older clients need it to stay connected. The new seed is sprout.radicle.xyz and setzling is for development purposes.
