### ISSUE TITLE
Docs mismatch with getting started page

### ISSUE THREAD

**Issue by PatrickAlphaC** [radicle-dev/radicle-docs#173]
The [getting started docs](https://docs.radicle.xyz/getting-started) page says to install with cargo, but the [getting started page](https://radicle.network/get-started.html) says to use cargo.

Can we please fix? Please point users to one canonical location.

**Comment by PatrickAlphaC** [comment]
And then [Try it](https://radicle.xyz/tryit) says to download apps!

Can we please streamline this process.

**Comment by pinkforest** [comment]
Oh this needs to be updated to match what is in https://github.com/radicle-dev/radicle-cli

`cargo install radicle-cli --force --locked --git https://seed.alt-clients.radicle.xyz/radicle-cli.git`

You can use Docker container from there too

**Comment by pinkforest** [comment]
Fix here: https://github.com/radicle-dev/radicle-docs/pull/175

Thanks for reporting

**Comment by PatrickAlphaC** [comment]
This is good, but it still doesn't address the issue. I'm saying developers are getting pulled into 3 different getting started places. 

Which one is the right one? This needs to be clear across the website and docs.

**Comment by pinkforest** [comment]
Yeah we definitely should link to one canonical place as these will get easily out of date -

FWIW - We may just do curl radup.sh that will greatly simplify this flow and is more future proof.

And thanks a lot for the feedback and persistence on this.

**Comment by PatrickAlphaC** [comment]
Does it make sense to close this issue though? It hasn't been solved...

**Comment by PatrickAlphaC** [comment]
Also:

```
cargo install radicle-cli --force --locked --git https://seed.alt-clients.radicle.xyz/radicle-cli.git
```

Is still not working for me.

**Comment by adam-hurwitz** [comment]
I posted a potentially similar issue where the Get started with Radicle site is not up-to-date with the Radicle CLI repository.

*See [ Get started with Radicle URL needs to be updated for Homebrew #280](https://github.com/radicle-dev/radicle-cli/issues/280)*
