### ISSUE TITLE
error: could not find `radicle-cli` in https://seed.alt-clients.radicle.xyz/radicle-cli.git with version `*`

### ISSUE THREAD

**Issue by PatrickAlphaC** [radicle-dev/radicle-docs#174]
Per the [radicle docs](https://docs.radicle.xyz/getting-started#install-the-radicle-cli) getting started page, we should run the following:

```
$ cargo install --force --locked --git https://seed.alt-clients.radicle.xyz/radicle-cli.git radicle-cli
```

However, running that will get us:

```
    Updating git repository `https://seed.alt-clients.radicle.xyz/radicle-cli.git`
error: could not find `radicle-cli` in https://seed.alt-clients.radicle.xyz/radicle-cli.git with version `*`
```

**Comment by pinkforest** [comment]
Fixing in #175 - Thanks for reporting.

Oh this needs to be updated to match what is in https://github.com/radicle-dev/radicle-cli that got updated today

`cargo install radicle-cli --force --locked --git https://seed.alt-clients.radicle.xyz/radicle-cli.git`
