### ISSUE TITLE
Add instructions for rad-cli

### ISSUE THREAD

**Issue by LoveIsGrief** [radicle-dev/radicle-docs#176]
The docs are mostly written for `upstream` which some radicle-cli commands in there. For example, [submitting a patch](https://docs.radicle.xyz/using-radicle/create-submit-patch) is only with `upstream` commands, while [creating a project](https://docs.radicle.xyz/using-radicle/create) is only with `rad` commands.

It would be great if there were a version of the instructions for radicle-cli and another for `upstream`.

Maybe something like this

![image](https://user-images.githubusercontent.com/2829538/184553964-b79e46de-a4c0-451b-8f34-fa536207adcc.png)

**Comment by joelhans** [comment]
Thanks for the feedback. I'll be working on removing all the Upstream content this week, which should clarify *some* of this. But I'll also likely end up moving much of the content about performing specific tasks into more use case-driven guides—something like, *How to collaborate with your peers on a Radicle project*. Stay tuned!

**Comment by joelhans** [comment]
Closing, as this work will likely fall to the Clients team.
