### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by idhsaineimad** [radicle-dev/radicle-docs#177]
I think this link in the introduction page is broken

[Radicle CLI](https://app.radicle.network/alt-clients.radicle.eth/rad:git:hnrkmg77m8tfzj4gi4pa4mbhgysfgzwntjpao/tree)

**Comment by joelhans** [comment]
Hi there! Looks like the link works OK for me—both here and in the docs—so I'll close this for now. Might have been a temporary downtime. If you see the issue persist, definitely let us know.
