### ISSUE TITLE
Patch and Issue workflow via rad binary

### ISSUE THREAD

**Issue by amoweolubusayo** [radicle-dev/radicle-docs#180]
This works via CLI, it would be a helpful addition to docs.

**Comment by joelhans** [comment]
Definitely! This is part of the plan for the next few weeks—stay tuned.

If you have any feedback on the process as it exists now, or any tips/tricks you might have found in your personal workflows, I'd love to hear about it.

**Comment by joelhans** [comment]
Partially resolved by #189

**Comment by joelhans** [comment]
Closing, as this work will likely fall to the Clients team.
