### ISSUE TITLE
Finish migration of Notion-based documentation

### ISSUE THREAD

**Issue by joelhans** [radicle-dev/radicle-docs#221]
I spent some time looking through the existing Notion-based hubs to find other information we should think about migrating over here. Here's what I found.

- [Contributor Hub](https://forest-text-046.notion.site/Radicle-Contributor-Hub-1627f61d92aa46c7b35776d4528e421c)
  - [Guide to Discord](https://forest-text-046.notion.site/Guide-to-Discord-ac7d0d19371c49c0990154a8789e2e1e): The information is out-of-date (reference to Upstream) but it may be nice to have documents about how we handle Discord internally.
  - [Core Teams](https://forest-text-046.notion.site/Core-Teams-8faf6989047a40dab77959469b456f90): We need to rethink how this information is presented, and update everything, but with all the DAO-level changes (e.g. Core Dev Org) happening right now, we might be better off waiting until the dust has settled.
  - [Radicle Contributor Directory](https://forest-text-046.notion.site/Radicle-Contributor-Directory-public-f70a7bdb8ae4408eb6c2d1783c9ce08f): Love the concept behind this, but we'd need to compile an up-to-date list, and maybe have the same blocker due to restructuring.
  - [Join the Radicle project](https://forest-text-046.notion.site/Join-the-Radicle-Project-12d6577fcc9d455b8626b2134e5166a8): Are these jobs current? It would be nice to supplement jobs with info on other contributor roles (both paid and non-paid), Grants, and more.

- [Governance Hub](https://forest-text-046.notion.site/Radicle-Governance-Hub-01b9f8e757cc4426ab64d2146071f46b#0bee09d2b4654bc88cecedeef92bb281)
  - I actually think we got most everything here, minus more complete descriptions of/links to the Grants program.

Once we decide on what to migrate, scope out the work, and build processes around updating them, we should also have a discussion about sunsetting some of these pages/hubs remove confusion and focus attention on `docs.radicle.community`.

**Comment by shelbeeee** [comment]
Given the changes to brand/organization of websites & docs that are being discussed at the moment, I think all of these additional resources will need to be reimagined before putting them anywhere.

- Guide to Discord: Depending on the branding split, it sounds like there may be multiple Discord servers. We just need to make sure we have clear pointers on each end to make sure folks find where they need to go. 
- Core Teams: This may also become irrelevant....it may be more helpful to just have "Org descriptions" or an Org Directory
- Radicle Contrib Directory: We should also revisit this. Although it is super helpful to have a centralized resources like this, with the direction this split is going it may make more sense for each org to manage this themselves? 
- Jobs page: This is something I think we should have on our main page. You may have already seen this on Discord, but I really like the type of information ENS has on their DAO domain page: https://ens.domains/governance/  (see top menu bar). Even though hiring will be done within the Orgs, I think it would still be great to have a centralized job board that maybe the operations or marketing team manages/coordinates with the different Orgs. 

Re Gov Hub: I want to take another look at this (and all governance resources we have worked on the past few months) and make sure that they still make sense given these recent changes, so there might be some changes there. This will be my main focus tomorrow..

**Comment by joelhans** [comment]
Makes sense, @shelbeeee! Let me know if you come up with any more TODOs, but no action on these necessary right now—I mostly wanted to create an inventory of assets that we shouldn't forget.

I do really like the ENS site. I feel like Brandon would be able to whip one together pretty quickly, and it lessens the burden on the documentation as being the sole resource for discovering governance/community-related links.

**Comment by shelbeeee** [comment]
I actually think we can resolve this issue. With the new Discord reorg there will be a clear section on Discord for this information. The new website will link out to the jobs board directly. The new docs pages have a page to link out to a planned contributor directory - this will come a bit later, but is still covered.  

If no objections, I will close this issue.

**Comment by joelhans** [comment]
No objections from me! I created this issue long before the brand split and all the recent work, so all the ideas are probably obsolete by now.
