### ISSUE TITLE
docs.radicle.community final cleanups

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#222]
hey @joelhans, here are the final updates I think we need to make to docs.radicle.community before "releasing".

* Remove User Documentation section and Sidebar. We're currently discussing repurposing this on the clients team website but for now, would like to remove from this site for clarity.
* Change "Radicle Documentation" to "RadicleDAO Documentation"
* Remove "Browse Radicle" nav bar link 
* Remove subtext (user documentation etc....) until we have something better!

cc @shelbeeee

**Comment by joelhans** [comment]
@abbey-titcomb Thanks for this! Working on it today—hopefully with a PR and deploy preview coming later today that we can review next week and discuss some more.

On the first point: I think for the time being I'll retain the documents themselves while hiding them from the navigation, so links to specific documents will still work until there is an alternative place for them to be housed/published.
