### ISSUE TITLE
Document that Apple Silicon is not a tested platform

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-docs#28]
We need to clearly communicate that we have not tested our software on the Apple Silicon platform. Until further notice this should be made explicit.

**Comment by abbey-titcomb** [comment]
Cool. Probably should include this in Troubleshooting? Or do we think on Getting Started page?

**Comment by xla** [comment]
Generally software docs have as one of the first sections the supported/tested platforms, often close to where the installation process is explained, together with the links to downloads.
