### ISSUE TITLE
[REVIEW] Getting Started & Using Radicle

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#3]
For any app team (tagged a couple, but anybody can review) that has been involved in building & designing the Upstream experience, I'd like your review on the structure and copy of our **Getting Started** and **Using Radicle** sections (see below):

Sections to Review: 
- docs/getting-started/getting-started
- docs/using-radicle/creating-and-sharing-projects
- docs/using-radicle/pushing-and-pulling-changes

We'd like these sections to satisfy the following conditions:
- The Getting Started section covers the necessary steps to get a user's profile & identity set-up clearly and successfully
- The Using Radicle sections outline all of the necessary actions available in the Upstream app
- The documentation outlines all CLI commands that will be involved in the user's experience

Feedback and comments can be discussed in this thread or implemented directly in a PR.

**Comment by MeBrei** [comment]
In the getting-started guide section [joining a seed node](https://github.com/radicle-dev/radicle-docs/blob/master/docs/getting-started/getting-started.md#joining-a-seed-node): Isn't `the official Radicle seed node` currently always added automatically as a default?

**Comment by rudolfs** [comment]
@MeBrei yeah, I already corrected that here: https://github.com/radicle-dev/radicle-docs/pull/13/files#diff-649b2d3ef0f2bb0bc9ba8ea8fe05493a20be64b3e26f302b84f9be36cbbde5b6.
