### ISSUE TITLE
Make docs searchable

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-docs#46]
Docs search would be helpful.

**Comment by abbey-titcomb** [comment]
@rudolfs or @MeBrei - this could be an easy one to pick up if you're around. Found this how-to enable search:

https://docusaurus.io/docs/en/search

**Comment by rudolfs** [comment]
TODO:
- [x] apply for an account at https://docsearch.algolia.com/apply
- [ ] configure docusaurus: https://docusaurus.io/docs/en/search#enabling-the-search-bar
- [ ] deploy and verify it works
