### ISSUE TITLE
Fix twitter previews

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#58]
Right now, there aren't very pretty Twitter previews when we link our Docs. Would love to have this fixed for when we share docs on Twitter.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/18275452/100542803-52029d00-3244-11eb-877f-5bb6b5e0c7c3.png">

**Comment by sebastinez** [comment]
I think what is missing here is to add a MetaImage to the ThemeConfig
https://docusaurus.io/docs/api/themes/configuration#meta-image

I'm not sure which logo to take and it cannot be svg, could you give me a hand here? @brandonhaslegs  
The description already improved significantly.
