### ISSUE TITLE
Update glossary 

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#7]
Mirror to make sure work from [#836](https://github.com/radicle-dev/radicle-upstream/issues/836) is captured and implemented.

**Comment by brandonhaslegs** [comment]
I'm seeing a lot of "PeerID" which if I understand correctly is called "Device ID" now. Should I make a separate issue or is that part of this?

**Comment by abbey-titcomb** [comment]
@brandonhaslegs - I can update in the PR

**Comment by brandonhaslegs** [comment]
Cool and I did just make an issue #25 to calm my ol' nerves.
