### ISSUE TITLE
Any docs.radicle.xyz URL is censored in Twitter 

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#80]
Shown as "Tweet is not available"

**Comment by rudolfs** [comment]
Worked for me here: https://twitter.com/rudolfs/status/1333472304093933568

**Comment by abbey-titcomb** [comment]
What about this one? https://twitter.com/radicle/status/1333473104597749761?s=20

**Comment by rudolfs** [comment]
> What about this one? https://twitter.com/radicle/status/1333473104597749761?s=20

<img width="588" alt="Screenshot 2020-11-30 at 19 42 10" src="https://user-images.githubusercontent.com/158411/100650388-25ce4580-3344-11eb-8196-479717b2794b.png">

**Comment by abbey-titcomb** [comment]
Wow, then guess this is just a personal problem. Will close, but we should note when it stops working again.
