### ISSUE TITLE
Add a button to make it easier for people to contribute to the docs

### ISSUE THREAD

**Issue by aspiers** [radicle-dev/radicle-docs#88]
It would be great if every page on https://docs.radicle.xyz/ had some kind of button in one of the page corners which would make it obvious how to contribute to the docs (e.g. by fixing a typo or reporting an issue).  Some other projects have a ["Fork me on Github" ribbon](https://forkmeon.github.io/) or similar so this might be one approach.

**Comment by gsaslis** [comment]
As someone who wants to make a contribution to the docs, I'm here to add my +1 and ... 

I see there is documentation around this feature [here](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#editUrl). 

Not sure what version of docusaurus radicle-docs are using, but perhaps this could just be a matter of enabling the feature?

**Comment by rudolfs** [comment]
Wonder if we could maybe switch to a local index?
https://docusaurus.io/docs/search#using-local-search

It shouldn't be too big for our docs.

**Comment by joelhans** [comment]
@rudolfs That actually worked quite well! I didn't know there was a local option, which is super convenient for circumventing all horrible things Docsearch. Check out #170 to see it in action!

**Comment by gsaslis** [comment]
Awesome - thanks for this @joelhans ! 🎉

**Comment by gsaslis** [comment]
... and @rudolfs !!! 😅
