### ISSUE TITLE
Add NixOS to list of Supported Platforms

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#96]
A contributor just built and merged a Nix package for radicle-upstream. We can add this to the list of Supported Platforms on the Getting Started page.

https://github.com/NixOS/nixpkgs/pull/105674#event-4114917389

**Comment by abbey-titcomb** [comment]
@FintanH - should I just directly link this (NixOS/nixpkgs#105674 (comment)) ? What's the protocol for Nix packages.

**Comment by FintanH** [comment]
It's currently available on the `unstable` channel and it can be installed by running `nix-env -iA nixos.radicle-upstream`

**Comment by xla** [comment]
When we add this as supported platform let's highlight that it's a third-party package.
