### ISSUE TITLE
Document additional identity creation 

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-docs#97]
Once https://github.com/radicle-dev/radicle-upstream/pull/1489 will be released, we can document how a user can set up a new identity. In the first version, there will be no ui for this, so that we can give some command line instructions. As a minimum, these instructions should be added to the troubleshooting document, to react to errors when creating an identity (eg key already exists) or if the user forgets their password.

**Comment by rudolfs** [comment]
This is now possible via `rad auth --init` and is [already documented](https://docs.radicle.xyz/docs/understanding-radicle/faq#whats-the-difference-between-a-peer-id-a-personal-urn-and-a-project-urn).
