### ISSUE TITLE
Rewrite the How it Works section

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/radicle-docs#99]
Radicle Link documentation Round 2! We've known we have to do a second iteration on the Radicle Link documentation, and this piece captured some great feedback on how we can improve it!

http://blog.vmsplice.net/2020/12/understanding-peer-to-peer-git-forges.html

**Comment by cloudhead** [comment]
I think we need a deep but non-implementation oriented write-up. So basically not a spec, but something that really explains things well, kind of like https://ssbc.github.io/scuttlebutt-protocol-guide/ or https://datprotocol.github.io/how-dat-works/

**Comment by pinkforest** [comment]
Tour of Dgraph is probably a good one where people get to play with it and by that way learn how it works:

https://dgraph.io/tour/

Bonus is that it can be used to validate any UX flows automatically we've defined where the output is recorded corresponding to input behaviours - both to docs and CI - e.g. when something changes somewhere we can then both validate everything still works and generate docs out of it - bonus is usually it is in the same place where the code is so it stays in sync with this.

But yes Tour of Dgraph is more structured education but it's very hands on / practical that may be of use.

**Comment by joelhans** [comment]
Working on this at #194
